import 'package:flutter/material.dart';

import 'home_screen_data.dart';

List<ProductModel> smoothiesList = [
  ProductModel(
    productName: 'watermelon juice',
    currency: '₹',
    productPrice: 39.00,
    bgColors: const [Color(0xFFF26C9C), Color(0xFFEC90E9)],
    productImage: 'assets/images/Group 2137.png',
    productSize: '200ml',
    productCount: 1,
  ),
  ProductModel(
    productName: 'mango juice',
    currency: '₹',
    productPrice: 44.00,
    bgColors: const [Color(0xFFFD9B8D), Color(0xFFFBBE7E)],
    productImage: 'assets/images/Group 2204.png',
    productSize: '200ml',
    productCount: 1,
  ),
  ProductModel(
    productName: 'blueberry juice',
    currency: '₹',
    productPrice: 60.00,
    bgColors: const [Color(0xFFA076E8), Color(0xFFB1C4F8)],
    productImage: 'assets/images/Group 2206.png',
    productSize: '200ml',
    productCount: 1,
  ),
  ProductModel(
    productName: 'avocado juice',
    currency: '₹',
    productPrice: 60.00,
    bgColors: const [Color(0xFF5CCD92), Color(0xFFBFE89C)],
    productImage: 'assets/images/Group 2207.png',
    productSize: '200ml',
    productCount: 1,
  ),
  ProductModel(
    productName: 'grape juice',
    currency: '₹',
    productPrice: 65.00,
    bgColors: const [Color(0xFFA86FDA), Color(0xFFF5B9D5)],
    productImage: 'assets/images/Group 2208.png',
    productSize: '200ml',
    productCount: 1,
  ),
  ProductModel(
    productName: 'apple',
    currency: '₹',
    productPrice: 49.00,
    bgColors: const [Color(0xFFF4787C), Color(0xFFFBA6C6)],
    productImage: 'assets/images/apple.png',
    productSize: '10 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'watermelon',
    currency: '₹',
    productPrice: 16.00,
    bgColors: const [Color(0xFFF26C9C), Color(0xFFEC90E9)],
    productImage: 'assets/images/watermelon.png',
    productSize: '1 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'mango',
    currency: '₹',
    productPrice: 19.00,
    bgColors: const [Color(0xFFFD9B8D), Color(0xFFFBBE7E)],
    productImage: 'assets/images/mango.png',
    productSize: '7 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'blueberry',
    currency: '₹',
    productPrice: 99.00,
    bgColors: const [Color(0xFFA076E8), Color(0xFFB1C4F8)],
    productImage: 'assets/images/blueberry.png',
    productSize: '100 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'avocado',
    currency: '₹',
    productPrice: 48.00,
    bgColors: const [Color(0xFF5CCD92), Color(0xFFBFE89C)],
    productImage: 'assets/images/avocado.png',
    productSize: '3 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'grapes',
    currency: '₹',
    productPrice: 99.00,
    bgColors: const [Color(0xFFA86FDA), Color(0xFFF5B9D5)],
    productImage: 'assets/images/grapes.png',
    productSize: '100 pieces',
    productCount: 1,
  ),
  ProductModel(
    productName: 'apple',
    currency: '₹',
    productPrice: 70.00,
    bgColors: const [Color(0xFFF4787C), Color(0xFFFBA6C6)],
    productImage: 'assets/images/apple.png',
    productSize: '10 pieces',
    productCount: 1,
  ),
];
